

export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored just for You",
        description: "Get interview questions and model answers based on your role, experience and specific focus areas - no generic practice here."
    },
    {
        id: "02",
        title: "Learn at your Own Pace",
        description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
    },
    {
        id: "03",
        title: "Capture Your Insights",
        description: "Add personal notes to any question and pin important ones to the top -- making your learning more organized and impactful."
    },
    {
        id: "04",
        title: 'Understand the "Why" Behind Answers',
        description: "Beyond just answers -- unlock detailed concept explanations generated by AI, helping you truly master each topic."
    },
    {
        id: "05",
        title: "Save, Organize and Revisit",
        description: "Easly save your interview sets, organize them neatly in your dashboard and pick up your preparation right where you left off."
    },
];